version: "3.8"
services:
  namingserver:
    container_name: namingserver
#    build:
#      context: .
#      dockerfile: NamingServerDockerfile
    image: maxitosh/namingserver:latest
    environment:
      - "PYTHONUNBUFFERED=1"
    entrypoint: ["python3", "NamingServer.py"]
#    volumes:
#    - .:/usr/src/app/
    ports:
      - 8800:8800

  mongodb:
    image: mongo:latest
    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "1234"
#      MONGO_INITDB_DATABASE: "DFS"
    ports:
      - 27017:27017
    volumes:
      - ./MongoDB/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./MongoDB/data:/data/db/
      - ./MongoDB/:/usr/src/app/
#networks:
#  default:
#    external:
#      name: alpine-net